# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 344e3f70f21aa6954259ac4b3ca524feb472d7f5f4978cc294b9ae5f2037732a332be95cce72c2f2c37a44b71bb261573c839f42428b82b5d2d3182c942e16ca

test:
  secret_key_base: a076811eed721dd5fdc0cb808ab0fe1b55c2228b28c1e2f920499a74f3074c0ff5cc99157634ff0f7bd58f8beda6e69bbe71400ac3f16e288dc2dd39bd966fbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
